/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the OrganizationForPrometheus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationForPrometheus{}

// OrganizationForPrometheus struct for OrganizationForPrometheus
type OrganizationForPrometheus struct {
	OrganizationId *int32 `json:"organizationId,omitempty"`
	OrganizationName NullableString `json:"organizationName,omitempty"`
	RuleDiscountRate *float64 `json:"ruleDiscountRate,omitempty"`
	GlobalDiscountRate *float64 `json:"globalDiscountRate,omitempty"`
}

// NewOrganizationForPrometheus instantiates a new OrganizationForPrometheus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationForPrometheus() *OrganizationForPrometheus {
	this := OrganizationForPrometheus{}
	return &this
}

// NewOrganizationForPrometheusWithDefaults instantiates a new OrganizationForPrometheus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationForPrometheusWithDefaults() *OrganizationForPrometheus {
	this := OrganizationForPrometheus{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *OrganizationForPrometheus) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationForPrometheus) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OrganizationForPrometheus) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *OrganizationForPrometheus) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationForPrometheus) GetOrganizationName() string {
	if o == nil || IsNil(o.OrganizationName.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationName.Get()
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationForPrometheus) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationName.Get(), o.OrganizationName.IsSet()
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *OrganizationForPrometheus) HasOrganizationName() bool {
	if o != nil && o.OrganizationName.IsSet() {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given NullableString and assigns it to the OrganizationName field.
func (o *OrganizationForPrometheus) SetOrganizationName(v string) {
	o.OrganizationName.Set(&v)
}
// SetOrganizationNameNil sets the value for OrganizationName to be an explicit nil
func (o *OrganizationForPrometheus) SetOrganizationNameNil() {
	o.OrganizationName.Set(nil)
}

// UnsetOrganizationName ensures that no value is present for OrganizationName, not even an explicit nil
func (o *OrganizationForPrometheus) UnsetOrganizationName() {
	o.OrganizationName.Unset()
}

// GetRuleDiscountRate returns the RuleDiscountRate field value if set, zero value otherwise.
func (o *OrganizationForPrometheus) GetRuleDiscountRate() float64 {
	if o == nil || IsNil(o.RuleDiscountRate) {
		var ret float64
		return ret
	}
	return *o.RuleDiscountRate
}

// GetRuleDiscountRateOk returns a tuple with the RuleDiscountRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationForPrometheus) GetRuleDiscountRateOk() (*float64, bool) {
	if o == nil || IsNil(o.RuleDiscountRate) {
		return nil, false
	}
	return o.RuleDiscountRate, true
}

// HasRuleDiscountRate returns a boolean if a field has been set.
func (o *OrganizationForPrometheus) HasRuleDiscountRate() bool {
	if o != nil && !IsNil(o.RuleDiscountRate) {
		return true
	}

	return false
}

// SetRuleDiscountRate gets a reference to the given float64 and assigns it to the RuleDiscountRate field.
func (o *OrganizationForPrometheus) SetRuleDiscountRate(v float64) {
	o.RuleDiscountRate = &v
}

// GetGlobalDiscountRate returns the GlobalDiscountRate field value if set, zero value otherwise.
func (o *OrganizationForPrometheus) GetGlobalDiscountRate() float64 {
	if o == nil || IsNil(o.GlobalDiscountRate) {
		var ret float64
		return ret
	}
	return *o.GlobalDiscountRate
}

// GetGlobalDiscountRateOk returns a tuple with the GlobalDiscountRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationForPrometheus) GetGlobalDiscountRateOk() (*float64, bool) {
	if o == nil || IsNil(o.GlobalDiscountRate) {
		return nil, false
	}
	return o.GlobalDiscountRate, true
}

// HasGlobalDiscountRate returns a boolean if a field has been set.
func (o *OrganizationForPrometheus) HasGlobalDiscountRate() bool {
	if o != nil && !IsNil(o.GlobalDiscountRate) {
		return true
	}

	return false
}

// SetGlobalDiscountRate gets a reference to the given float64 and assigns it to the GlobalDiscountRate field.
func (o *OrganizationForPrometheus) SetGlobalDiscountRate(v float64) {
	o.GlobalDiscountRate = &v
}

func (o OrganizationForPrometheus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationForPrometheus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if o.OrganizationName.IsSet() {
		toSerialize["organizationName"] = o.OrganizationName.Get()
	}
	if !IsNil(o.RuleDiscountRate) {
		toSerialize["ruleDiscountRate"] = o.RuleDiscountRate
	}
	if !IsNil(o.GlobalDiscountRate) {
		toSerialize["globalDiscountRate"] = o.GlobalDiscountRate
	}
	return toSerialize, nil
}

type NullableOrganizationForPrometheus struct {
	value *OrganizationForPrometheus
	isSet bool
}

func (v NullableOrganizationForPrometheus) Get() *OrganizationForPrometheus {
	return v.value
}

func (v *NullableOrganizationForPrometheus) Set(val *OrganizationForPrometheus) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationForPrometheus) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationForPrometheus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationForPrometheus(val *OrganizationForPrometheus) *NullableOrganizationForPrometheus {
	return &NullableOrganizationForPrometheus{value: val, isSet: true}
}

func (v NullableOrganizationForPrometheus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationForPrometheus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


