/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the BridgeListCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BridgeListCommand{}

// BridgeListCommand struct for BridgeListCommand
type BridgeListCommand struct {
	Url string `json:"url"`
	Username string `json:"username"`
	Password string `json:"password"`
	Hypervisor string `json:"hypervisor"`
}

// NewBridgeListCommand instantiates a new BridgeListCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBridgeListCommand(url string, username string, password string, hypervisor string) *BridgeListCommand {
	this := BridgeListCommand{}
	this.Url = url
	this.Username = username
	this.Password = password
	this.Hypervisor = hypervisor
	return &this
}

// NewBridgeListCommandWithDefaults instantiates a new BridgeListCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBridgeListCommandWithDefaults() *BridgeListCommand {
	this := BridgeListCommand{}
	return &this
}

// GetUrl returns the Url field value
func (o *BridgeListCommand) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BridgeListCommand) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BridgeListCommand) SetUrl(v string) {
	o.Url = v
}

// GetUsername returns the Username field value
func (o *BridgeListCommand) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *BridgeListCommand) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *BridgeListCommand) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *BridgeListCommand) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *BridgeListCommand) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *BridgeListCommand) SetPassword(v string) {
	o.Password = v
}

// GetHypervisor returns the Hypervisor field value
func (o *BridgeListCommand) GetHypervisor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hypervisor
}

// GetHypervisorOk returns a tuple with the Hypervisor field value
// and a boolean to check if the value has been set.
func (o *BridgeListCommand) GetHypervisorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hypervisor, true
}

// SetHypervisor sets field value
func (o *BridgeListCommand) SetHypervisor(v string) {
	o.Hypervisor = v
}

func (o BridgeListCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BridgeListCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	toSerialize["hypervisor"] = o.Hypervisor
	return toSerialize, nil
}

type NullableBridgeListCommand struct {
	value *BridgeListCommand
	isSet bool
}

func (v NullableBridgeListCommand) Get() *BridgeListCommand {
	return v.value
}

func (v *NullableBridgeListCommand) Set(val *BridgeListCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgeListCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgeListCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgeListCommand(val *BridgeListCommand) *NullableBridgeListCommand {
	return &NullableBridgeListCommand{value: val, isSet: true}
}

func (v NullableBridgeListCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgeListCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


