/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the ArtifactUrlCheckerCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactUrlCheckerCommand{}

// ArtifactUrlCheckerCommand struct for ArtifactUrlCheckerCommand
type ArtifactUrlCheckerCommand struct {
	Url NullableString `json:"url,omitempty"`
	Name string `json:"name"`
}

// NewArtifactUrlCheckerCommand instantiates a new ArtifactUrlCheckerCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactUrlCheckerCommand(name string) *ArtifactUrlCheckerCommand {
	this := ArtifactUrlCheckerCommand{}
	this.Name = name
	return &this
}

// NewArtifactUrlCheckerCommandWithDefaults instantiates a new ArtifactUrlCheckerCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactUrlCheckerCommandWithDefaults() *ArtifactUrlCheckerCommand {
	this := ArtifactUrlCheckerCommand{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArtifactUrlCheckerCommand) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtifactUrlCheckerCommand) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *ArtifactUrlCheckerCommand) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *ArtifactUrlCheckerCommand) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *ArtifactUrlCheckerCommand) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *ArtifactUrlCheckerCommand) UnsetUrl() {
	o.Url.Unset()
}

// GetName returns the Name field value
func (o *ArtifactUrlCheckerCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ArtifactUrlCheckerCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ArtifactUrlCheckerCommand) SetName(v string) {
	o.Name = v
}

func (o ArtifactUrlCheckerCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactUrlCheckerCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableArtifactUrlCheckerCommand struct {
	value *ArtifactUrlCheckerCommand
	isSet bool
}

func (v NullableArtifactUrlCheckerCommand) Get() *ArtifactUrlCheckerCommand {
	return v.value
}

func (v *NullableArtifactUrlCheckerCommand) Set(val *ArtifactUrlCheckerCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactUrlCheckerCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactUrlCheckerCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactUrlCheckerCommand(val *ArtifactUrlCheckerCommand) *NullableArtifactUrlCheckerCommand {
	return &NullableArtifactUrlCheckerCommand{value: val, isSet: true}
}

func (v NullableArtifactUrlCheckerCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactUrlCheckerCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


