/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the CreateTanzuCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTanzuCommand{}

// CreateTanzuCommand struct for CreateTanzuCommand
type CreateTanzuCommand struct {
	OrganizationId NullableInt32 `json:"organizationId,omitempty"`
	Name string `json:"name"`
	Username string `json:"username"`
	Url string `json:"url"`
	Password string `json:"password"`
	VolumeType string `json:"volumeType"`
	Namespace string `json:"namespace"`
	TanzuContinent NullableString `json:"tanzuContinent,omitempty"`
	Port NullableInt32 `json:"port,omitempty"`
}

// NewCreateTanzuCommand instantiates a new CreateTanzuCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTanzuCommand(name string, username string, url string, password string, volumeType string, namespace string) *CreateTanzuCommand {
	this := CreateTanzuCommand{}
	this.Name = name
	this.Username = username
	this.Url = url
	this.Password = password
	this.VolumeType = volumeType
	this.Namespace = namespace
	return &this
}

// NewCreateTanzuCommandWithDefaults instantiates a new CreateTanzuCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTanzuCommandWithDefaults() *CreateTanzuCommand {
	this := CreateTanzuCommand{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTanzuCommand) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId.Get()) {
		var ret int32
		return ret
	}
	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTanzuCommand) GetOrganizationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CreateTanzuCommand) HasOrganizationId() bool {
	if o != nil && o.OrganizationId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given NullableInt32 and assigns it to the OrganizationId field.
func (o *CreateTanzuCommand) SetOrganizationId(v int32) {
	o.OrganizationId.Set(&v)
}
// SetOrganizationIdNil sets the value for OrganizationId to be an explicit nil
func (o *CreateTanzuCommand) SetOrganizationIdNil() {
	o.OrganizationId.Set(nil)
}

// UnsetOrganizationId ensures that no value is present for OrganizationId, not even an explicit nil
func (o *CreateTanzuCommand) UnsetOrganizationId() {
	o.OrganizationId.Unset()
}

// GetName returns the Name field value
func (o *CreateTanzuCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTanzuCommand) SetName(v string) {
	o.Name = v
}

// GetUsername returns the Username field value
func (o *CreateTanzuCommand) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateTanzuCommand) SetUsername(v string) {
	o.Username = v
}

// GetUrl returns the Url field value
func (o *CreateTanzuCommand) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateTanzuCommand) SetUrl(v string) {
	o.Url = v
}

// GetPassword returns the Password field value
func (o *CreateTanzuCommand) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateTanzuCommand) SetPassword(v string) {
	o.Password = v
}

// GetVolumeType returns the VolumeType field value
func (o *CreateTanzuCommand) GetVolumeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VolumeType
}

// GetVolumeTypeOk returns a tuple with the VolumeType field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetVolumeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VolumeType, true
}

// SetVolumeType sets field value
func (o *CreateTanzuCommand) SetVolumeType(v string) {
	o.VolumeType = v
}

// GetNamespace returns the Namespace field value
func (o *CreateTanzuCommand) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *CreateTanzuCommand) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *CreateTanzuCommand) SetNamespace(v string) {
	o.Namespace = v
}

// GetTanzuContinent returns the TanzuContinent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTanzuCommand) GetTanzuContinent() string {
	if o == nil || IsNil(o.TanzuContinent.Get()) {
		var ret string
		return ret
	}
	return *o.TanzuContinent.Get()
}

// GetTanzuContinentOk returns a tuple with the TanzuContinent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTanzuCommand) GetTanzuContinentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TanzuContinent.Get(), o.TanzuContinent.IsSet()
}

// HasTanzuContinent returns a boolean if a field has been set.
func (o *CreateTanzuCommand) HasTanzuContinent() bool {
	if o != nil && o.TanzuContinent.IsSet() {
		return true
	}

	return false
}

// SetTanzuContinent gets a reference to the given NullableString and assigns it to the TanzuContinent field.
func (o *CreateTanzuCommand) SetTanzuContinent(v string) {
	o.TanzuContinent.Set(&v)
}
// SetTanzuContinentNil sets the value for TanzuContinent to be an explicit nil
func (o *CreateTanzuCommand) SetTanzuContinentNil() {
	o.TanzuContinent.Set(nil)
}

// UnsetTanzuContinent ensures that no value is present for TanzuContinent, not even an explicit nil
func (o *CreateTanzuCommand) UnsetTanzuContinent() {
	o.TanzuContinent.Unset()
}

// GetPort returns the Port field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateTanzuCommand) GetPort() int32 {
	if o == nil || IsNil(o.Port.Get()) {
		var ret int32
		return ret
	}
	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateTanzuCommand) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// HasPort returns a boolean if a field has been set.
func (o *CreateTanzuCommand) HasPort() bool {
	if o != nil && o.Port.IsSet() {
		return true
	}

	return false
}

// SetPort gets a reference to the given NullableInt32 and assigns it to the Port field.
func (o *CreateTanzuCommand) SetPort(v int32) {
	o.Port.Set(&v)
}
// SetPortNil sets the value for Port to be an explicit nil
func (o *CreateTanzuCommand) SetPortNil() {
	o.Port.Set(nil)
}

// UnsetPort ensures that no value is present for Port, not even an explicit nil
func (o *CreateTanzuCommand) UnsetPort() {
	o.Port.Unset()
}

func (o CreateTanzuCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTanzuCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrganizationId.IsSet() {
		toSerialize["organizationId"] = o.OrganizationId.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["username"] = o.Username
	toSerialize["url"] = o.Url
	toSerialize["password"] = o.Password
	toSerialize["volumeType"] = o.VolumeType
	toSerialize["namespace"] = o.Namespace
	if o.TanzuContinent.IsSet() {
		toSerialize["tanzuContinent"] = o.TanzuContinent.Get()
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	return toSerialize, nil
}

type NullableCreateTanzuCommand struct {
	value *CreateTanzuCommand
	isSet bool
}

func (v NullableCreateTanzuCommand) Get() *CreateTanzuCommand {
	return v.value
}

func (v *NullableCreateTanzuCommand) Set(val *CreateTanzuCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTanzuCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTanzuCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTanzuCommand(val *CreateTanzuCommand) *NullableCreateTanzuCommand {
	return &NullableCreateTanzuCommand{value: val, isSet: true}
}

func (v NullableCreateTanzuCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTanzuCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


