/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikungoclient

import (
	"encoding/json"
	"time"
)

// checks if the CreateBillingSummaryCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBillingSummaryCommand{}

// CreateBillingSummaryCommand struct for CreateBillingSummaryCommand
type CreateBillingSummaryCommand struct {
	Icu int32 `json:"icu"`
	BeginApply *time.Time `json:"beginApply,omitempty"`
	ProjectId int32 `json:"projectId"`
}

// NewCreateBillingSummaryCommand instantiates a new CreateBillingSummaryCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBillingSummaryCommand(icu int32, projectId int32) *CreateBillingSummaryCommand {
	this := CreateBillingSummaryCommand{}
	this.Icu = icu
	this.ProjectId = projectId
	return &this
}

// NewCreateBillingSummaryCommandWithDefaults instantiates a new CreateBillingSummaryCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBillingSummaryCommandWithDefaults() *CreateBillingSummaryCommand {
	this := CreateBillingSummaryCommand{}
	return &this
}

// GetIcu returns the Icu field value
func (o *CreateBillingSummaryCommand) GetIcu() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Icu
}

// GetIcuOk returns a tuple with the Icu field value
// and a boolean to check if the value has been set.
func (o *CreateBillingSummaryCommand) GetIcuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icu, true
}

// SetIcu sets field value
func (o *CreateBillingSummaryCommand) SetIcu(v int32) {
	o.Icu = v
}

// GetBeginApply returns the BeginApply field value if set, zero value otherwise.
func (o *CreateBillingSummaryCommand) GetBeginApply() time.Time {
	if o == nil || IsNil(o.BeginApply) {
		var ret time.Time
		return ret
	}
	return *o.BeginApply
}

// GetBeginApplyOk returns a tuple with the BeginApply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBillingSummaryCommand) GetBeginApplyOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BeginApply) {
		return nil, false
	}
	return o.BeginApply, true
}

// HasBeginApply returns a boolean if a field has been set.
func (o *CreateBillingSummaryCommand) HasBeginApply() bool {
	if o != nil && !IsNil(o.BeginApply) {
		return true
	}

	return false
}

// SetBeginApply gets a reference to the given time.Time and assigns it to the BeginApply field.
func (o *CreateBillingSummaryCommand) SetBeginApply(v time.Time) {
	o.BeginApply = &v
}

// GetProjectId returns the ProjectId field value
func (o *CreateBillingSummaryCommand) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CreateBillingSummaryCommand) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CreateBillingSummaryCommand) SetProjectId(v int32) {
	o.ProjectId = v
}

func (o CreateBillingSummaryCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBillingSummaryCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icu"] = o.Icu
	if !IsNil(o.BeginApply) {
		toSerialize["beginApply"] = o.BeginApply
	}
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

type NullableCreateBillingSummaryCommand struct {
	value *CreateBillingSummaryCommand
	isSet bool
}

func (v NullableCreateBillingSummaryCommand) Get() *CreateBillingSummaryCommand {
	return v.value
}

func (v *NullableCreateBillingSummaryCommand) Set(val *CreateBillingSummaryCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBillingSummaryCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBillingSummaryCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBillingSummaryCommand(val *CreateBillingSummaryCommand) *NullableCreateBillingSummaryCommand {
	return &NullableCreateBillingSummaryCommand{value: val, isSet: true}
}

func (v NullableCreateBillingSummaryCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBillingSummaryCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


