/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikungoclient

import (
	"encoding/json"
)

// checks if the RestartStsCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestartStsCommand{}

// RestartStsCommand struct for RestartStsCommand
type RestartStsCommand struct {
	ProjectId int32 `json:"projectId"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
}

// NewRestartStsCommand instantiates a new RestartStsCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestartStsCommand(projectId int32, name string, namespace string) *RestartStsCommand {
	this := RestartStsCommand{}
	this.ProjectId = projectId
	this.Name = name
	this.Namespace = namespace
	return &this
}

// NewRestartStsCommandWithDefaults instantiates a new RestartStsCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartStsCommandWithDefaults() *RestartStsCommand {
	this := RestartStsCommand{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *RestartStsCommand) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *RestartStsCommand) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *RestartStsCommand) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetName returns the Name field value
func (o *RestartStsCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RestartStsCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RestartStsCommand) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *RestartStsCommand) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *RestartStsCommand) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *RestartStsCommand) SetNamespace(v string) {
	o.Namespace = v
}

func (o RestartStsCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartStsCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace
	return toSerialize, nil
}

type NullableRestartStsCommand struct {
	value *RestartStsCommand
	isSet bool
}

func (v NullableRestartStsCommand) Get() *RestartStsCommand {
	return v.value
}

func (v *NullableRestartStsCommand) Set(val *RestartStsCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartStsCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartStsCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartStsCommand(val *RestartStsCommand) *NullableRestartStsCommand {
	return &NullableRestartStsCommand{value: val, isSet: true}
}

func (v NullableRestartStsCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartStsCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


