/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the TransferTicketCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferTicketCommand{}

// TransferTicketCommand struct for TransferTicketCommand
type TransferTicketCommand struct {
	TicketId string `json:"ticketId"`
	UserId string `json:"userId"`
}

// NewTransferTicketCommand instantiates a new TransferTicketCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferTicketCommand(ticketId string, userId string) *TransferTicketCommand {
	this := TransferTicketCommand{}
	this.TicketId = ticketId
	this.UserId = userId
	return &this
}

// NewTransferTicketCommandWithDefaults instantiates a new TransferTicketCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferTicketCommandWithDefaults() *TransferTicketCommand {
	this := TransferTicketCommand{}
	return &this
}

// GetTicketId returns the TicketId field value
func (o *TransferTicketCommand) GetTicketId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TicketId
}

// GetTicketIdOk returns a tuple with the TicketId field value
// and a boolean to check if the value has been set.
func (o *TransferTicketCommand) GetTicketIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TicketId, true
}

// SetTicketId sets field value
func (o *TransferTicketCommand) SetTicketId(v string) {
	o.TicketId = v
}

// GetUserId returns the UserId field value
func (o *TransferTicketCommand) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *TransferTicketCommand) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *TransferTicketCommand) SetUserId(v string) {
	o.UserId = v
}

func (o TransferTicketCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferTicketCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ticketId"] = o.TicketId
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

type NullableTransferTicketCommand struct {
	value *TransferTicketCommand
	isSet bool
}

func (v NullableTransferTicketCommand) Get() *TransferTicketCommand {
	return v.value
}

func (v *NullableTransferTicketCommand) Set(val *TransferTicketCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferTicketCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferTicketCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferTicketCommand(val *TransferTicketCommand) *NullableTransferTicketCommand {
	return &NullableTransferTicketCommand{value: val, isSet: true}
}

func (v NullableTransferTicketCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferTicketCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


