/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the VmTemplateListCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmTemplateListCommand{}

// VmTemplateListCommand struct for VmTemplateListCommand
type VmTemplateListCommand struct {
	Url string `json:"url"`
	Username string `json:"username"`
	Password string `json:"password"`
}

// NewVmTemplateListCommand instantiates a new VmTemplateListCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmTemplateListCommand(url string, username string, password string) *VmTemplateListCommand {
	this := VmTemplateListCommand{}
	this.Url = url
	this.Username = username
	this.Password = password
	return &this
}

// NewVmTemplateListCommandWithDefaults instantiates a new VmTemplateListCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmTemplateListCommandWithDefaults() *VmTemplateListCommand {
	this := VmTemplateListCommand{}
	return &this
}

// GetUrl returns the Url field value
func (o *VmTemplateListCommand) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *VmTemplateListCommand) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *VmTemplateListCommand) SetUrl(v string) {
	o.Url = v
}

// GetUsername returns the Username field value
func (o *VmTemplateListCommand) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *VmTemplateListCommand) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *VmTemplateListCommand) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *VmTemplateListCommand) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *VmTemplateListCommand) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *VmTemplateListCommand) SetPassword(v string) {
	o.Password = v
}

func (o VmTemplateListCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmTemplateListCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableVmTemplateListCommand struct {
	value *VmTemplateListCommand
	isSet bool
}

func (v NullableVmTemplateListCommand) Get() *VmTemplateListCommand {
	return v.value
}

func (v *NullableVmTemplateListCommand) Set(val *VmTemplateListCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableVmTemplateListCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableVmTemplateListCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmTemplateListCommand(val *VmTemplateListCommand) *NullableVmTemplateListCommand {
	return &NullableVmTemplateListCommand{value: val, isSet: true}
}

func (v NullableVmTemplateListCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmTemplateListCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


