/*
Taikun - Showback API

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikunshowback

import (
	"encoding/json"
)

// checks if the GroupedCredentialForShowbackSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedCredentialForShowbackSummary{}

// GroupedCredentialForShowbackSummary struct for GroupedCredentialForShowbackSummary
type GroupedCredentialForShowbackSummary struct {
	Id *int32 `json:"id,omitempty"`
	ProjectId *int32 `json:"projectId,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewGroupedCredentialForShowbackSummary instantiates a new GroupedCredentialForShowbackSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedCredentialForShowbackSummary() *GroupedCredentialForShowbackSummary {
	this := GroupedCredentialForShowbackSummary{}
	return &this
}

// NewGroupedCredentialForShowbackSummaryWithDefaults instantiates a new GroupedCredentialForShowbackSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedCredentialForShowbackSummaryWithDefaults() *GroupedCredentialForShowbackSummary {
	this := GroupedCredentialForShowbackSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GroupedCredentialForShowbackSummary) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedCredentialForShowbackSummary) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GroupedCredentialForShowbackSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GroupedCredentialForShowbackSummary) SetId(v int32) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GroupedCredentialForShowbackSummary) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedCredentialForShowbackSummary) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GroupedCredentialForShowbackSummary) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GroupedCredentialForShowbackSummary) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupedCredentialForShowbackSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedCredentialForShowbackSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupedCredentialForShowbackSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupedCredentialForShowbackSummary) SetName(v string) {
	o.Name = &v
}

func (o GroupedCredentialForShowbackSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedCredentialForShowbackSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGroupedCredentialForShowbackSummary struct {
	value *GroupedCredentialForShowbackSummary
	isSet bool
}

func (v NullableGroupedCredentialForShowbackSummary) Get() *GroupedCredentialForShowbackSummary {
	return v.value
}

func (v *NullableGroupedCredentialForShowbackSummary) Set(val *GroupedCredentialForShowbackSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedCredentialForShowbackSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedCredentialForShowbackSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedCredentialForShowbackSummary(val *GroupedCredentialForShowbackSummary) *NullableGroupedCredentialForShowbackSummary {
	return &NullableGroupedCredentialForShowbackSummary{value: val, isSet: true}
}

func (v NullableGroupedCredentialForShowbackSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedCredentialForShowbackSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


