/*
Taikun - Showback API

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikunshowback

import (
	"encoding/json"
)

// checks if the CreateShowbackRuleCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateShowbackRuleCommand{}

// CreateShowbackRuleCommand struct for CreateShowbackRuleCommand
type CreateShowbackRuleCommand struct {
	Name *string `json:"name,omitempty"`
	MetricName *string `json:"metricName,omitempty"`
	ByLabel *string `json:"byLabel,omitempty"`
	Kind *EShowbackType `json:"kind,omitempty"`
	Type *EPrometheusType `json:"type,omitempty"`
	Price *float64 `json:"price,omitempty"`
	ProjectAlertLimit *int32 `json:"projectAlertLimit,omitempty"`
	GlobalAlertLimit *int32 `json:"globalAlertLimit,omitempty"`
	OrganizationId *int32 `json:"organizationId,omitempty"`
	Labels []ShowbackLabelCreateDto `json:"labels,omitempty"`
	ShowbackCredentialId *int32 `json:"showbackCredentialId,omitempty"`
}

// NewCreateShowbackRuleCommand instantiates a new CreateShowbackRuleCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShowbackRuleCommand() *CreateShowbackRuleCommand {
	this := CreateShowbackRuleCommand{}
	return &this
}

// NewCreateShowbackRuleCommandWithDefaults instantiates a new CreateShowbackRuleCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShowbackRuleCommandWithDefaults() *CreateShowbackRuleCommand {
	this := CreateShowbackRuleCommand{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateShowbackRuleCommand) SetName(v string) {
	o.Name = &v
}

// GetMetricName returns the MetricName field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetMetricName() string {
	if o == nil || IsNil(o.MetricName) {
		var ret string
		return ret
	}
	return *o.MetricName
}

// GetMetricNameOk returns a tuple with the MetricName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetMetricNameOk() (*string, bool) {
	if o == nil || IsNil(o.MetricName) {
		return nil, false
	}
	return o.MetricName, true
}

// HasMetricName returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasMetricName() bool {
	if o != nil && !IsNil(o.MetricName) {
		return true
	}

	return false
}

// SetMetricName gets a reference to the given string and assigns it to the MetricName field.
func (o *CreateShowbackRuleCommand) SetMetricName(v string) {
	o.MetricName = &v
}

// GetByLabel returns the ByLabel field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetByLabel() string {
	if o == nil || IsNil(o.ByLabel) {
		var ret string
		return ret
	}
	return *o.ByLabel
}

// GetByLabelOk returns a tuple with the ByLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetByLabelOk() (*string, bool) {
	if o == nil || IsNil(o.ByLabel) {
		return nil, false
	}
	return o.ByLabel, true
}

// HasByLabel returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasByLabel() bool {
	if o != nil && !IsNil(o.ByLabel) {
		return true
	}

	return false
}

// SetByLabel gets a reference to the given string and assigns it to the ByLabel field.
func (o *CreateShowbackRuleCommand) SetByLabel(v string) {
	o.ByLabel = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetKind() EShowbackType {
	if o == nil || IsNil(o.Kind) {
		var ret EShowbackType
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetKindOk() (*EShowbackType, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given EShowbackType and assigns it to the Kind field.
func (o *CreateShowbackRuleCommand) SetKind(v EShowbackType) {
	o.Kind = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetType() EPrometheusType {
	if o == nil || IsNil(o.Type) {
		var ret EPrometheusType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetTypeOk() (*EPrometheusType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given EPrometheusType and assigns it to the Type field.
func (o *CreateShowbackRuleCommand) SetType(v EPrometheusType) {
	o.Type = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetPrice() float64 {
	if o == nil || IsNil(o.Price) {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *CreateShowbackRuleCommand) SetPrice(v float64) {
	o.Price = &v
}

// GetProjectAlertLimit returns the ProjectAlertLimit field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetProjectAlertLimit() int32 {
	if o == nil || IsNil(o.ProjectAlertLimit) {
		var ret int32
		return ret
	}
	return *o.ProjectAlertLimit
}

// GetProjectAlertLimitOk returns a tuple with the ProjectAlertLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetProjectAlertLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectAlertLimit) {
		return nil, false
	}
	return o.ProjectAlertLimit, true
}

// HasProjectAlertLimit returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasProjectAlertLimit() bool {
	if o != nil && !IsNil(o.ProjectAlertLimit) {
		return true
	}

	return false
}

// SetProjectAlertLimit gets a reference to the given int32 and assigns it to the ProjectAlertLimit field.
func (o *CreateShowbackRuleCommand) SetProjectAlertLimit(v int32) {
	o.ProjectAlertLimit = &v
}

// GetGlobalAlertLimit returns the GlobalAlertLimit field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetGlobalAlertLimit() int32 {
	if o == nil || IsNil(o.GlobalAlertLimit) {
		var ret int32
		return ret
	}
	return *o.GlobalAlertLimit
}

// GetGlobalAlertLimitOk returns a tuple with the GlobalAlertLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetGlobalAlertLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.GlobalAlertLimit) {
		return nil, false
	}
	return o.GlobalAlertLimit, true
}

// HasGlobalAlertLimit returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasGlobalAlertLimit() bool {
	if o != nil && !IsNil(o.GlobalAlertLimit) {
		return true
	}

	return false
}

// SetGlobalAlertLimit gets a reference to the given int32 and assigns it to the GlobalAlertLimit field.
func (o *CreateShowbackRuleCommand) SetGlobalAlertLimit(v int32) {
	o.GlobalAlertLimit = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *CreateShowbackRuleCommand) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetLabels() []ShowbackLabelCreateDto {
	if o == nil || IsNil(o.Labels) {
		var ret []ShowbackLabelCreateDto
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetLabelsOk() ([]ShowbackLabelCreateDto, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []ShowbackLabelCreateDto and assigns it to the Labels field.
func (o *CreateShowbackRuleCommand) SetLabels(v []ShowbackLabelCreateDto) {
	o.Labels = v
}

// GetShowbackCredentialId returns the ShowbackCredentialId field value if set, zero value otherwise.
func (o *CreateShowbackRuleCommand) GetShowbackCredentialId() int32 {
	if o == nil || IsNil(o.ShowbackCredentialId) {
		var ret int32
		return ret
	}
	return *o.ShowbackCredentialId
}

// GetShowbackCredentialIdOk returns a tuple with the ShowbackCredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateShowbackRuleCommand) GetShowbackCredentialIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ShowbackCredentialId) {
		return nil, false
	}
	return o.ShowbackCredentialId, true
}

// HasShowbackCredentialId returns a boolean if a field has been set.
func (o *CreateShowbackRuleCommand) HasShowbackCredentialId() bool {
	if o != nil && !IsNil(o.ShowbackCredentialId) {
		return true
	}

	return false
}

// SetShowbackCredentialId gets a reference to the given int32 and assigns it to the ShowbackCredentialId field.
func (o *CreateShowbackRuleCommand) SetShowbackCredentialId(v int32) {
	o.ShowbackCredentialId = &v
}

func (o CreateShowbackRuleCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShowbackRuleCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.MetricName) {
		toSerialize["metricName"] = o.MetricName
	}
	if !IsNil(o.ByLabel) {
		toSerialize["byLabel"] = o.ByLabel
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.ProjectAlertLimit) {
		toSerialize["projectAlertLimit"] = o.ProjectAlertLimit
	}
	if !IsNil(o.GlobalAlertLimit) {
		toSerialize["globalAlertLimit"] = o.GlobalAlertLimit
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.ShowbackCredentialId) {
		toSerialize["showbackCredentialId"] = o.ShowbackCredentialId
	}
	return toSerialize, nil
}

type NullableCreateShowbackRuleCommand struct {
	value *CreateShowbackRuleCommand
	isSet bool
}

func (v NullableCreateShowbackRuleCommand) Get() *CreateShowbackRuleCommand {
	return v.value
}

func (v *NullableCreateShowbackRuleCommand) Set(val *CreateShowbackRuleCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShowbackRuleCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShowbackRuleCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShowbackRuleCommand(val *CreateShowbackRuleCommand) *NullableCreateShowbackRuleCommand {
	return &NullableCreateShowbackRuleCommand{value: val, isSet: true}
}

func (v NullableCreateShowbackRuleCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShowbackRuleCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


