/*
Taikun - Showback API

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikunshowback

import (
	"encoding/json"
)

// checks if the GroupedProjectForShowbackSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedProjectForShowbackSummary{}

// GroupedProjectForShowbackSummary struct for GroupedProjectForShowbackSummary
type GroupedProjectForShowbackSummary struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	TotalPrice *float64 `json:"totalPrice,omitempty"`
	IsDeleted *bool `json:"isDeleted,omitempty"`
}

// NewGroupedProjectForShowbackSummary instantiates a new GroupedProjectForShowbackSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedProjectForShowbackSummary() *GroupedProjectForShowbackSummary {
	this := GroupedProjectForShowbackSummary{}
	return &this
}

// NewGroupedProjectForShowbackSummaryWithDefaults instantiates a new GroupedProjectForShowbackSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedProjectForShowbackSummaryWithDefaults() *GroupedProjectForShowbackSummary {
	this := GroupedProjectForShowbackSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GroupedProjectForShowbackSummary) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedProjectForShowbackSummary) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GroupedProjectForShowbackSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GroupedProjectForShowbackSummary) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupedProjectForShowbackSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedProjectForShowbackSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupedProjectForShowbackSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupedProjectForShowbackSummary) SetName(v string) {
	o.Name = &v
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise.
func (o *GroupedProjectForShowbackSummary) GetTotalPrice() float64 {
	if o == nil || IsNil(o.TotalPrice) {
		var ret float64
		return ret
	}
	return *o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedProjectForShowbackSummary) GetTotalPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalPrice) {
		return nil, false
	}
	return o.TotalPrice, true
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *GroupedProjectForShowbackSummary) HasTotalPrice() bool {
	if o != nil && !IsNil(o.TotalPrice) {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given float64 and assigns it to the TotalPrice field.
func (o *GroupedProjectForShowbackSummary) SetTotalPrice(v float64) {
	o.TotalPrice = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *GroupedProjectForShowbackSummary) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedProjectForShowbackSummary) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *GroupedProjectForShowbackSummary) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *GroupedProjectForShowbackSummary) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

func (o GroupedProjectForShowbackSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedProjectForShowbackSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TotalPrice) {
		toSerialize["totalPrice"] = o.TotalPrice
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	return toSerialize, nil
}

type NullableGroupedProjectForShowbackSummary struct {
	value *GroupedProjectForShowbackSummary
	isSet bool
}

func (v NullableGroupedProjectForShowbackSummary) Get() *GroupedProjectForShowbackSummary {
	return v.value
}

func (v *NullableGroupedProjectForShowbackSummary) Set(val *GroupedProjectForShowbackSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedProjectForShowbackSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedProjectForShowbackSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedProjectForShowbackSummary(val *GroupedProjectForShowbackSummary) *NullableGroupedProjectForShowbackSummary {
	return &NullableGroupedProjectForShowbackSummary{value: val, isSet: true}
}

func (v NullableGroupedProjectForShowbackSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedProjectForShowbackSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


